#include "mainwindow.h"
#include "connectwindow.h"

#include <QApplication>

// <KADE DEMO>
#include "db_comms.h" // A sample header for db communication
#include "connection.pb.h"    // The file generated by protoc
// </KADE DEMO>

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);

    // <KADE DEMO>
    db_comms *db = new db_comms();
    QString result = db->get_connect_result();
    Logger::Log("FIRST LOG: " + result); // Should print "Dummy Test ID" which is set in new db_communication();

    QSharedPointer<db_connection::ConnectResult> res_obj = db->get_connect_result_object();
    Logger::Log("SECOND LOG: " + QString::fromStdString(res_obj->id())); // Should also print "Dummy Test ID"
    // </KADE DEMO>

    // MainWindow w;
    ConnectWindow c;
    c.show();
    return a.exec();
}
